import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import * as reactor from '../reactor';
import PageLayout from '../components/PageLayout';

export async function getStaticProps(context) {
  reactor.init();
  const data = await reactor.getModular('PcDI6UBZsHluOmA3R98o');
  console.log(data);
  return {
    props: {
      frames: [],
      revalidate: 10
    }
  };
}

export default function Home({ frames }) {
  // console.log(frames);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PageLayout />
    </>
  );
}
